export const BUY_LAPTOP="BUY_LAPTOP";
export const BUY_MOBILE="BUY_MOBILE";
export const FETCH_USERS_REQUEST="FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL="FETCH_USERS_FAIL";